// Package webhook is the HTTP boundary: it turns an inbound Superset webhook
// request into Telegram messages.
package webhook

import (
	"context"
	"errors"
	"io"
	"log/slog"
	"net/http"

	"github.com/dengaleev/superset-telegram-bridge/internal/message"
	"github.com/dengaleev/superset-telegram-bridge/internal/superset"
	"github.com/dengaleev/superset-telegram-bridge/internal/telegram"
)

// maxBodyBytes bounds request bodies (screenshots/PDFs); over this the caller is
// rejected. Telegram's own per-file limits apply downstream.
const maxBodyBytes = 50 << 20 // 50 MiB

// Sender is the subset of *telegram.Client the handler needs; an interface so
// tests can mock it (see ./mocks, generated by mockery — regenerate with `mockery`).
type Sender interface {
	SendMessage(ctx context.Context, chatID, text string) error
	SendPhoto(ctx context.Context, chatID, caption string, m telegram.Media) error
	SendDocument(ctx context.Context, chatID, caption string, m telegram.Media) error
	SendMediaGroup(ctx context.Context, chatID, caption, kind string, files []telegram.Media) error
}

// Handler returns the POST /webhook handler: it reads the body, parses the
// Superset payload, and forwards it (text or attachments) to Telegram.
func Handler(tg Sender, chatID string, logger *slog.Logger) http.HandlerFunc {
	return func(w http.ResponseWriter, r *http.Request) {
		ctx := r.Context()
		body, err := io.ReadAll(http.MaxBytesReader(w, r.Body, maxBodyBytes))
		if err != nil {
			if _, ok := errors.AsType[*http.MaxBytesError](err); ok {
				logger.WarnContext(ctx, "request body too large", "limit", maxBodyBytes)
				http.Error(w, "request body too large", http.StatusRequestEntityTooLarge)
				return
			}
			logger.WarnContext(ctx, "read request body", "error", err)
			http.Error(w, "cannot read body", http.StatusBadRequest)
			return
		}

		payload, err := superset.Parse(r.Header.Get("Content-Type"), body)
		if err != nil {
			if errors.Is(err, superset.ErrUnsupportedMediaType) {
				http.Error(w, "unsupported media type", http.StatusUnsupportedMediaType)
				return
			}
			logger.WarnContext(ctx, "parse payload", "error", err)
			http.Error(w, "invalid payload", http.StatusBadRequest)
			return
		}

		if err := forward(ctx, tg, chatID, logger, payload); err != nil {
			logger.ErrorContext(ctx, "forward to telegram", "error", err)
			http.Error(w, "upstream error", http.StatusBadGateway)
			return
		}
		w.WriteHeader(http.StatusNoContent)
	}
}

// forward sends the payload to Telegram: a plain message when there are no files,
// otherwise photos (image/png) and documents (everything else) — single sends for
// one file, albums for several.
func forward(ctx context.Context, tg Sender, chatID string, logger *slog.Logger, p superset.Payload) error {
	if len(p.Files) == 0 {
		return tg.SendMessage(ctx, chatID, message.Render(p, message.TextMaxLen))
	}

	var photos, docs []telegram.Media
	for _, f := range p.Files {
		m := telegram.Media{Filename: f.Filename, MIME: f.MIME, Data: f.Data}
		if f.MIME == "image/png" {
			photos = append(photos, m)
		} else {
			docs = append(docs, m)
		}
	}

	caption := message.Render(p, message.CaptionMaxLen)
	if len(photos) > 0 {
		if err := sendGroup(ctx, tg, chatID, caption, "photo", photos, logger); err != nil {
			return err
		}
		caption = "" // caption already delivered with the photos
	}
	if len(docs) > 0 {
		if err := sendGroup(ctx, tg, chatID, caption, "document", docs, logger); err != nil {
			return err
		}
	}
	return nil
}

// sendGroup sends one MIME class: a single photo/document, or an album of 2..N.
// kind is "photo" or "document" (set by the caller's MIME split) and selects the
// single-send method. Telegram albums cap at MaxMediaGroup, so overflow is dropped.
func sendGroup(ctx context.Context, tg Sender, chatID, caption, kind string, files []telegram.Media, logger *slog.Logger) error {
	if len(files) > telegram.MaxMediaGroup {
		logger.WarnContext(ctx, "dropping attachments over Telegram album limit",
			"kind", kind, "kept", telegram.MaxMediaGroup, "dropped", len(files)-telegram.MaxMediaGroup)
		files = files[:telegram.MaxMediaGroup]
	}
	switch {
	case len(files) == 1 && kind == "photo":
		return tg.SendPhoto(ctx, chatID, caption, files[0])
	case len(files) == 1:
		return tg.SendDocument(ctx, chatID, caption, files[0])
	default:
		return tg.SendMediaGroup(ctx, chatID, caption, kind, files)
	}
}
