// Code generated by mockery v2.53.6. DO NOT EDIT.

package mocks

import (
	context "context"

	telegram "github.com/dengaleev/superset-telegram-bridge/internal/telegram"
	mock "github.com/stretchr/testify/mock"
)

// MockSender is an autogenerated mock type for the Sender type
type MockSender struct {
	mock.Mock
}

type MockSender_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSender) EXPECT() *MockSender_Expecter {
	return &MockSender_Expecter{mock: &_m.Mock}
}

// SendDocument provides a mock function with given fields: ctx, chatID, caption, m
func (_m *MockSender) SendDocument(ctx context.Context, chatID string, caption string, m telegram.Media) error {
	ret := _m.Called(ctx, chatID, caption, m)

	if len(ret) == 0 {
		panic("no return value specified for SendDocument")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, telegram.Media) error); ok {
		r0 = rf(ctx, chatID, caption, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_SendDocument_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendDocument'
type MockSender_SendDocument_Call struct {
	*mock.Call
}

// SendDocument is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - caption string
//   - m telegram.Media
func (_e *MockSender_Expecter) SendDocument(ctx interface{}, chatID interface{}, caption interface{}, m interface{}) *MockSender_SendDocument_Call {
	return &MockSender_SendDocument_Call{Call: _e.mock.On("SendDocument", ctx, chatID, caption, m)}
}

func (_c *MockSender_SendDocument_Call) Run(run func(ctx context.Context, chatID string, caption string, m telegram.Media)) *MockSender_SendDocument_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(telegram.Media))
	})
	return _c
}

func (_c *MockSender_SendDocument_Call) Return(_a0 error) *MockSender_SendDocument_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_SendDocument_Call) RunAndReturn(run func(context.Context, string, string, telegram.Media) error) *MockSender_SendDocument_Call {
	_c.Call.Return(run)
	return _c
}

// SendMediaGroup provides a mock function with given fields: ctx, chatID, caption, kind, files
func (_m *MockSender) SendMediaGroup(ctx context.Context, chatID string, caption string, kind string, files []telegram.Media) error {
	ret := _m.Called(ctx, chatID, caption, kind, files)

	if len(ret) == 0 {
		panic("no return value specified for SendMediaGroup")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, string, []telegram.Media) error); ok {
		r0 = rf(ctx, chatID, caption, kind, files)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_SendMediaGroup_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMediaGroup'
type MockSender_SendMediaGroup_Call struct {
	*mock.Call
}

// SendMediaGroup is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - caption string
//   - kind string
//   - files []telegram.Media
func (_e *MockSender_Expecter) SendMediaGroup(ctx interface{}, chatID interface{}, caption interface{}, kind interface{}, files interface{}) *MockSender_SendMediaGroup_Call {
	return &MockSender_SendMediaGroup_Call{Call: _e.mock.On("SendMediaGroup", ctx, chatID, caption, kind, files)}
}

func (_c *MockSender_SendMediaGroup_Call) Run(run func(ctx context.Context, chatID string, caption string, kind string, files []telegram.Media)) *MockSender_SendMediaGroup_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(string), args[4].([]telegram.Media))
	})
	return _c
}

func (_c *MockSender_SendMediaGroup_Call) Return(_a0 error) *MockSender_SendMediaGroup_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_SendMediaGroup_Call) RunAndReturn(run func(context.Context, string, string, string, []telegram.Media) error) *MockSender_SendMediaGroup_Call {
	_c.Call.Return(run)
	return _c
}

// SendMessage provides a mock function with given fields: ctx, chatID, text
func (_m *MockSender) SendMessage(ctx context.Context, chatID string, text string) error {
	ret := _m.Called(ctx, chatID, text)

	if len(ret) == 0 {
		panic("no return value specified for SendMessage")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string) error); ok {
		r0 = rf(ctx, chatID, text)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_SendMessage_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendMessage'
type MockSender_SendMessage_Call struct {
	*mock.Call
}

// SendMessage is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - text string
func (_e *MockSender_Expecter) SendMessage(ctx interface{}, chatID interface{}, text interface{}) *MockSender_SendMessage_Call {
	return &MockSender_SendMessage_Call{Call: _e.mock.On("SendMessage", ctx, chatID, text)}
}

func (_c *MockSender_SendMessage_Call) Run(run func(ctx context.Context, chatID string, text string)) *MockSender_SendMessage_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string))
	})
	return _c
}

func (_c *MockSender_SendMessage_Call) Return(_a0 error) *MockSender_SendMessage_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_SendMessage_Call) RunAndReturn(run func(context.Context, string, string) error) *MockSender_SendMessage_Call {
	_c.Call.Return(run)
	return _c
}

// SendPhoto provides a mock function with given fields: ctx, chatID, caption, m
func (_m *MockSender) SendPhoto(ctx context.Context, chatID string, caption string, m telegram.Media) error {
	ret := _m.Called(ctx, chatID, caption, m)

	if len(ret) == 0 {
		panic("no return value specified for SendPhoto")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, telegram.Media) error); ok {
		r0 = rf(ctx, chatID, caption, m)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// MockSender_SendPhoto_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'SendPhoto'
type MockSender_SendPhoto_Call struct {
	*mock.Call
}

// SendPhoto is a helper method to define mock.On call
//   - ctx context.Context
//   - chatID string
//   - caption string
//   - m telegram.Media
func (_e *MockSender_Expecter) SendPhoto(ctx interface{}, chatID interface{}, caption interface{}, m interface{}) *MockSender_SendPhoto_Call {
	return &MockSender_SendPhoto_Call{Call: _e.mock.On("SendPhoto", ctx, chatID, caption, m)}
}

func (_c *MockSender_SendPhoto_Call) Run(run func(ctx context.Context, chatID string, caption string, m telegram.Media)) *MockSender_SendPhoto_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(context.Context), args[1].(string), args[2].(string), args[3].(telegram.Media))
	})
	return _c
}

func (_c *MockSender_SendPhoto_Call) Return(_a0 error) *MockSender_SendPhoto_Call {
	_c.Call.Return(_a0)
	return _c
}

func (_c *MockSender_SendPhoto_Call) RunAndReturn(run func(context.Context, string, string, telegram.Media) error) *MockSender_SendPhoto_Call {
	_c.Call.Return(run)
	return _c
}

// NewMockSender creates a new instance of MockSender. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSender(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSender {
	mock := &MockSender{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
